# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

In [26]:
#boolean布尔型    float浮点型   int整型

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [27]:
num = 0
for i in range(100):
    if i % 2 == 0:
        num = num - i
    else:
        num = num + i
print(num)

50


1.3  将字符串 s="yoyo" 转换成列表

In [28]:
s="yoyo"
print(list(s))

['y', 'o', 'y', 'o']


# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的

In [29]:
# i是1到100中的数
#从第三个数字开始，每隔三个取；
#取最后十个数字。

2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [49]:
class HighMinusClose():
    def __init__(self,high,close):
        self.high = high
        self.close = close
    def one(self):
        return {'one_dif':self.high - self.close}
    def two(self):
        return {'two_dif':self.high - self.close}
print(HighMinusClose(15,7).one())
print(HighMinusClose(66,20).two())


{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

In [31]:
#查看列名：list(df)；数据转置：df.T

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [48]:
import pandas as pd
sheetnames=pd.ExcelFile('sz50.xlsx',on_demand=True).sheet_names
from datetime import datetime
data={}
for a in sheetnames:
    data[a]=pd.read_excel('sz50.xlsx',sheetname=0, index_col='datetime')
print(data.keys())

dict_keys(['600000.XSHG', '600016.XSHG', '600028.XSHG', '600029.XSHG', '600030.XSHG', '600036.XSHG', '600048.XSHG', '600050.XSHG', '600100.XSHG', '600104.XSHG', '600111.XSHG', '600340.XSHG', '600485.XSHG', '600518.XSHG', '600519.XSHG', '600547.XSHG', '600606.XSHG', '600837.XSHG', '600887.XSHG', '600919.XSHG', '600958.XSHG', '600999.XSHG', '601006.XSHG', '601088.XSHG', '601166.XSHG', '601169.XSHG', '601186.XSHG', '601198.XSHG', '601211.XSHG', '601229.XSHG', '601288.XSHG', '601318.XSHG', '601328.XSHG', '601336.XSHG', '601390.XSHG', '601398.XSHG', '601601.XSHG', '601628.XSHG', '601668.XSHG', '601688.XSHG', '601766.XSHG', '601788.XSHG', '601800.XSHG', '601818.XSHG', '601857.XSHG', '601881.XSHG', '601901.XSHG', '601985.XSHG', '601988.XSHG', '601989.XSHG'])


In [36]:
df=data['600029.XSHG']
import numpy as np
import talib as ta
close=np.array(df['close'])
print(ta.MA(close,10)[-5:])

[117.957 118.013 117.882 118.069 118.425]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [37]:
import pandas as pd

In [38]:
stocks=['600029.XSHG','600050.XSHG','601318.XSHG']
stocks_dict={}
for stock in stocks_dict:
    stocks_dict[stock]=data[stock]
stocks_pa=pd.Panel(stocks_dict)

D:\anaco\lib\site-packages\IPython\core\interactiveshell.py:3267: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


In [6]:
stocks=['600029.XSHG','600050.XSHG','601318.XSHG']
df=data['600029.XSHG']
import numpy as np
import talib as ta
close=np.array(df['close'])
print(ta.MA(close,10)[-5:])

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume

3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [46]:
M=np.array(stocks_pa)
print(M.shape)
print(M[:,-20:0])

(0, 0, 0)
[]


In [7]:
N=np.array(stocks_pa)
print(N.shape)
print(N[t,-20:0])

(3, 215, 5)
[[  13.85   13.82   13.83   14.11   14.25   14.39   15.1    15.15   15.22
    14.97   14.89   14.99   14.71   15.07   15.35   16.     16.04   16.29
    16.97   17.05]
 [   8.53    8.56    8.62    8.88    9.25    9.24    9.43    9.25    9.02
     9.15    9.63    9.5     9.9     9.97    9.96    9.49    9.68    9.61
     9.63    9.8 ]
 [ 134.83  134.56  137.5   143.18  143.48  144.15  143.61  143.65  144.35
   143.36  146.41  144.71  148.56  156.53  157.12  157.72  154.99  163.52
   168.58  169.57]]


3.5 建立一个5*5的矩阵，值从0到24

In [14]:
import numpy as np
arr=np.arange(25).reshape((5,5))  
print(arr) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
